// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/packet/message.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Body          *anypb.Any             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_packet_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

// 用于客户端建立连接后的身份验证
type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 客户端唯一标识符
	AppId         uint64                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`               // 应用ID
	Sign          string                 `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`                               // 签名
	ClientInfo    *ClientInfo            `protobuf:"bytes,4,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"` // 客户端信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_pkg_packet_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{1}
}

func (x *Login) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Login) GetAppId() uint64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Login) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *Login) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type ClientInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                       // 主机名
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                                       // 用户名
	Gid             string                 `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid,omitempty"`                                                 // 组ID
	Uid             string                 `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`                                                 // 用户ID
	OsName          string                 `protobuf:"bytes,5,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`                             // 操作系统名称
	OsArch          string                 `protobuf:"bytes,6,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`                             // 操作系统架构
	Uptime          uint64                 `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`                                          // 启动时间
	BootTime        uint64                 `protobuf:"varint,8,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`                      // 引导时间
	Os              string                 `protobuf:"bytes,9,opt,name=os,proto3" json:"os,omitempty"`                                                   // 操作系统
	Platform        string                 `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`                                      // 平台
	PlatformFamily  string                 `protobuf:"bytes,11,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`    // 平台家族
	PlatformVersion string                 `protobuf:"bytes,12,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"` // 平台版本
	KernelVersion   string                 `protobuf:"bytes,13,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`       // 内核版本
	KernelArch      string                 `protobuf:"bytes,14,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`                // 内核架构
	HostId          string                 `protobuf:"bytes,15,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                            // 主机ID
	CpuNum          int32                  `protobuf:"varint,16,opt,name=cpu_num,json=cpuNum,proto3" json:"cpu_num,omitempty"`                           // CPU数量
	CpuInfo         string                 `protobuf:"bytes,17,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`                         // CPU信息
	MemTotal        uint64                 `protobuf:"varint,18,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`                     // 内存总量
	DiskTotal       uint64                 `protobuf:"varint,19,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`                  // 磁盘总量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_pkg_packet_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientInfo) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *ClientInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClientInfo) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *ClientInfo) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *ClientInfo) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *ClientInfo) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *ClientInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ClientInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClientInfo) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *ClientInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *ClientInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *ClientInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *ClientInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ClientInfo) GetCpuNum() int32 {
	if x != nil {
		return x.CpuNum
	}
	return 0
}

func (x *ClientInfo) GetCpuInfo() string {
	if x != nil {
		return x.CpuInfo
	}
	return ""
}

func (x *ClientInfo) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *ClientInfo) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

type LoginAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAck) Reset() {
	*x = LoginAck{}
	mi := &file_pkg_packet_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAck) ProtoMessage() {}

func (x *LoginAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAck.ProtoReflect.Descriptor instead.
func (*LoginAck) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{3}
}

func (x *LoginAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorAck) Reset() {
	*x = ErrorAck{}
	mi := &file_pkg_packet_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorAck) ProtoMessage() {}

func (x *ErrorAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorAck.ProtoReflect.Descriptor instead.
func (*ErrorAck) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_packet_message_proto protoreflect.FileDescriptor

const file_pkg_packet_message_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/packet/message.proto\x12\bprotocol\x1a\x19google/protobuf/any.proto\"J\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12(\n" +
	"\x04body\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04body\"\x86\x01\n" +
	"\x05Login\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x04R\x05appId\x12\x12\n" +
	"\x04sign\x18\x03 \x01(\tR\x04sign\x125\n" +
	"\vclient_info\x18\x04 \x01(\v2\x14.protocol.ClientInfoR\n" +
	"clientInfo\"\xa0\x04\n" +
	"\n" +
	"ClientInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\tR\x03gid\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\x12\x17\n" +
	"\aos_name\x18\x05 \x01(\tR\x06osName\x12\x17\n" +
	"\aos_arch\x18\x06 \x01(\tR\x06osArch\x12\x16\n" +
	"\x06uptime\x18\a \x01(\x04R\x06uptime\x12\x1b\n" +
	"\tboot_time\x18\b \x01(\x04R\bbootTime\x12\x0e\n" +
	"\x02os\x18\t \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\n" +
	" \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\v \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\f \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\r \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vkernel_arch\x18\x0e \x01(\tR\n" +
	"kernelArch\x12\x17\n" +
	"\ahost_id\x18\x0f \x01(\tR\x06hostId\x12\x17\n" +
	"\acpu_num\x18\x10 \x01(\x05R\x06cpuNum\x12\x19\n" +
	"\bcpu_info\x18\x11 \x01(\tR\acpuInfo\x12\x1b\n" +
	"\tmem_total\x18\x12 \x01(\x04R\bmemTotal\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x13 \x01(\x04R\tdiskTotal\"8\n" +
	"\bLoginAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\bErrorAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x11Z\x0fnoah/pkg/packetb\x06proto3"

var (
	file_pkg_packet_message_proto_rawDescOnce sync.Once
	file_pkg_packet_message_proto_rawDescData []byte
)

func file_pkg_packet_message_proto_rawDescGZIP() []byte {
	file_pkg_packet_message_proto_rawDescOnce.Do(func() {
		file_pkg_packet_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_packet_message_proto_rawDesc), len(file_pkg_packet_message_proto_rawDesc)))
	})
	return file_pkg_packet_message_proto_rawDescData
}

var file_pkg_packet_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_packet_message_proto_goTypes = []any{
	(*Message)(nil),    // 0: protocol.Message
	(*Login)(nil),      // 1: protocol.Login
	(*ClientInfo)(nil), // 2: protocol.ClientInfo
	(*LoginAck)(nil),   // 3: protocol.LoginAck
	(*ErrorAck)(nil),   // 4: protocol.ErrorAck
	(*anypb.Any)(nil),  // 5: google.protobuf.Any
}
var file_pkg_packet_message_proto_depIdxs = []int32{
	5, // 0: protocol.Message.body:type_name -> google.protobuf.Any
	2, // 1: protocol.Login.client_info:type_name -> protocol.ClientInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_packet_message_proto_init() }
func file_pkg_packet_message_proto_init() {
	if File_pkg_packet_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_packet_message_proto_rawDesc), len(file_pkg_packet_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_packet_message_proto_goTypes,
		DependencyIndexes: file_pkg_packet_message_proto_depIdxs,
		MessageInfos:      file_pkg_packet_message_proto_msgTypes,
	}.Build()
	File_pkg_packet_message_proto = out.File
	file_pkg_packet_message_proto_goTypes = nil
	file_pkg_packet_message_proto_depIdxs = nil
}
