// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/packet/message.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenTunnel_TuunnelType int32

const (
	OpenTunnel_UNKNOWN OpenTunnel_TuunnelType = 0
	OpenTunnel_PTY     OpenTunnel_TuunnelType = 1
	OpenTunnel_TCP     OpenTunnel_TuunnelType = 2
	OpenTunnel_UDP     OpenTunnel_TuunnelType = 3
)

// Enum value maps for OpenTunnel_TuunnelType.
var (
	OpenTunnel_TuunnelType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PTY",
		2: "TCP",
		3: "UDP",
	}
	OpenTunnel_TuunnelType_value = map[string]int32{
		"UNKNOWN": 0,
		"PTY":     1,
		"TCP":     2,
		"UDP":     3,
	}
)

func (x OpenTunnel_TuunnelType) Enum() *OpenTunnel_TuunnelType {
	p := new(OpenTunnel_TuunnelType)
	*p = x
	return p
}

func (x OpenTunnel_TuunnelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenTunnel_TuunnelType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_packet_message_proto_enumTypes[0].Descriptor()
}

func (OpenTunnel_TuunnelType) Type() protoreflect.EnumType {
	return &file_pkg_packet_message_proto_enumTypes[0]
}

func (x OpenTunnel_TuunnelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenTunnel_TuunnelType.Descriptor instead.
func (OpenTunnel_TuunnelType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{6, 0}
}

type Command_Cmd int32

const (
	Command_UNKNOWN Command_Cmd = 0
	Command_EXIT    Command_Cmd = 1 // 退出程序
)

// Enum value maps for Command_Cmd.
var (
	Command_Cmd_name = map[int32]string{
		0: "UNKNOWN",
		1: "EXIT",
	}
	Command_Cmd_value = map[string]int32{
		"UNKNOWN": 0,
		"EXIT":    1,
	}
)

func (x Command_Cmd) Enum() *Command_Cmd {
	p := new(Command_Cmd)
	*p = x
	return p
}

func (x Command_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_packet_message_proto_enumTypes[1].Descriptor()
}

func (Command_Cmd) Type() protoreflect.EnumType {
	return &file_pkg_packet_message_proto_enumTypes[1]
}

func (x Command_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Cmd.Descriptor instead.
func (Command_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{8, 0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Body          *anypb.Any             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_packet_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

// 用于客户端建立连接后的身份验证
type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`    // 客户端唯一标识符
	AppId         uint64                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`            // 应用ID
	Sign          string                 `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`                            // 签名
	AgentInfo     *AgentInfo             `protobuf:"bytes,4,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"` // 客户端信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_pkg_packet_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Auth) GetAppId() uint64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Auth) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *Auth) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type AgentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                       // 主机名
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                                       // 用户名
	Gid             string                 `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid,omitempty"`                                                 // 组ID
	Uid             string                 `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`                                                 // 用户ID
	OsName          string                 `protobuf:"bytes,5,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`                             // 操作系统名称
	OsArch          string                 `protobuf:"bytes,6,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`                             // 操作系统架构
	Uptime          uint64                 `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`                                          // 启动时间
	BootTime        uint64                 `protobuf:"varint,8,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`                      // 引导时间
	Os              string                 `protobuf:"bytes,9,opt,name=os,proto3" json:"os,omitempty"`                                                   // 操作系统
	Platform        string                 `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`                                      // 平台
	PlatformFamily  string                 `protobuf:"bytes,11,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`    // 平台家族
	PlatformVersion string                 `protobuf:"bytes,12,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"` // 平台版本
	KernelVersion   string                 `protobuf:"bytes,13,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`       // 内核版本
	KernelArch      string                 `protobuf:"bytes,14,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`                // 内核架构
	HostId          string                 `protobuf:"bytes,15,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                            // 主机ID
	CpuNum          int32                  `protobuf:"varint,16,opt,name=cpu_num,json=cpuNum,proto3" json:"cpu_num,omitempty"`                           // CPU数量
	CpuInfo         string                 `protobuf:"bytes,17,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`                         // CPU信息
	MemTotal        uint64                 `protobuf:"varint,18,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`                     // 内存总量
	DiskTotal       uint64                 `protobuf:"varint,19,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`                  // 磁盘总量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pkg_packet_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AgentInfo) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *AgentInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AgentInfo) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *AgentInfo) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *AgentInfo) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *AgentInfo) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentInfo) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *AgentInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *AgentInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *AgentInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *AgentInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentInfo) GetCpuNum() int32 {
	if x != nil {
		return x.CpuNum
	}
	return 0
}

func (x *AgentInfo) GetCpuInfo() string {
	if x != nil {
		return x.CpuInfo
	}
	return ""
}

func (x *AgentInfo) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *AgentInfo) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

// 身份验证响应
type AuthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_pkg_packet_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{3}
}

func (x *AuthAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 心跳包
type Ping struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MemFree        uint64                 `protobuf:"varint,2,opt,name=mem_free,json=memFree,proto3" json:"mem_free,omitempty"`
	MemUsed        uint64                 `protobuf:"varint,3,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	MemUsedPercent float64                `protobuf:"fixed64,4,opt,name=mem_used_percent,json=memUsedPercent,proto3" json:"mem_used_percent,omitempty"`
	MemAvailable   uint64                 `protobuf:"varint,5,opt,name=mem_available,json=memAvailable,proto3" json:"mem_available,omitempty"`
	CpuPercent     float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	DiskUsage      []*DiskUsage           `protobuf:"bytes,7,rep,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetBytesSent   float64                `protobuf:"fixed64,8,opt,name=net_bytes_sent,json=netBytesSent,proto3" json:"net_bytes_sent,omitempty"`
	NetBytesRecv   float64                `protobuf:"fixed64,9,opt,name=net_bytes_recv,json=netBytesRecv,proto3" json:"net_bytes_recv,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pkg_packet_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ping) GetMemFree() uint64 {
	if x != nil {
		return x.MemFree
	}
	return 0
}

func (x *Ping) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *Ping) GetMemUsedPercent() float64 {
	if x != nil {
		return x.MemUsedPercent
	}
	return 0
}

func (x *Ping) GetMemAvailable() uint64 {
	if x != nil {
		return x.MemAvailable
	}
	return 0
}

func (x *Ping) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Ping) GetDiskUsage() []*DiskUsage {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

func (x *Ping) GetNetBytesSent() float64 {
	if x != nil {
		return x.NetBytesSent
	}
	return 0
}

func (x *Ping) GetNetBytesRecv() float64 {
	if x != nil {
		return x.NetBytesRecv
	}
	return 0
}

type DiskUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fstype            string                 `protobuf:"bytes,2,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Total             uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Free              uint64                 `protobuf:"varint,4,opt,name=free,proto3" json:"free,omitempty"`
	Used              uint64                 `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	UsedPercent       float64                `protobuf:"fixed64,6,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	InodesTotal       uint64                 `protobuf:"varint,7,opt,name=inodes_total,json=inodesTotal,proto3" json:"inodes_total,omitempty"`
	InodesFree        uint64                 `protobuf:"varint,8,opt,name=inodes_free,json=inodesFree,proto3" json:"inodes_free,omitempty"`
	InodesUsed        uint64                 `protobuf:"varint,9,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	InodesUsedPercent float64                `protobuf:"fixed64,10,opt,name=inodes_used_percent,json=inodesUsedPercent,proto3" json:"inodes_used_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_pkg_packet_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{5}
}

func (x *DiskUsage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskUsage) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *DiskUsage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskUsage) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DiskUsage) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskUsage) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *DiskUsage) GetInodesTotal() uint64 {
	if x != nil {
		return x.InodesTotal
	}
	return 0
}

func (x *DiskUsage) GetInodesFree() uint64 {
	if x != nil {
		return x.InodesFree
	}
	return 0
}

func (x *DiskUsage) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *DiskUsage) GetInodesUsedPercent() float64 {
	if x != nil {
		return x.InodesUsedPercent
	}
	return 0
}

// 打开终端
type OpenTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelType    OpenTunnel_TuunnelType `protobuf:"varint,1,opt,name=tunnel_type,json=tunnelType,proto3,enum=packet.OpenTunnel_TuunnelType" json:"tunnel_type,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnel) Reset() {
	*x = OpenTunnel{}
	mi := &file_pkg_packet_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnel) ProtoMessage() {}

func (x *OpenTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnel.ProtoReflect.Descriptor instead.
func (*OpenTunnel) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{6}
}

func (x *OpenTunnel) GetTunnelType() OpenTunnel_TuunnelType {
	if x != nil {
		return x.TunnelType
	}
	return OpenTunnel_UNKNOWN
}

func (x *OpenTunnel) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type OpenTunnelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnelAck) Reset() {
	*x = OpenTunnelAck{}
	mi := &file_pkg_packet_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelAck) ProtoMessage() {}

func (x *OpenTunnelAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelAck.ProtoReflect.Descriptor instead.
func (*OpenTunnelAck) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{7}
}

func (x *OpenTunnelAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OpenTunnelAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           Command_Cmd            `protobuf:"varint,1,opt,name=cmd,proto3,enum=packet.Command_Cmd" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkg_packet_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packet_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_packet_message_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetCmd() Command_Cmd {
	if x != nil {
		return x.Cmd
	}
	return Command_UNKNOWN
}

var File_pkg_packet_message_proto protoreflect.FileDescriptor

const file_pkg_packet_message_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/packet/message.proto\x12\x06packet\x1a\x19google/protobuf/any.proto\"J\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12(\n" +
	"\x04body\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04body\"\x80\x01\n" +
	"\x04Auth\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x04R\x05appId\x12\x12\n" +
	"\x04sign\x18\x03 \x01(\tR\x04sign\x120\n" +
	"\n" +
	"agent_info\x18\x04 \x01(\v2\x11.packet.AgentInfoR\tagentInfo\"\x9f\x04\n" +
	"\tAgentInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\tR\x03gid\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\x12\x17\n" +
	"\aos_name\x18\x05 \x01(\tR\x06osName\x12\x17\n" +
	"\aos_arch\x18\x06 \x01(\tR\x06osArch\x12\x16\n" +
	"\x06uptime\x18\a \x01(\x04R\x06uptime\x12\x1b\n" +
	"\tboot_time\x18\b \x01(\x04R\bbootTime\x12\x0e\n" +
	"\x02os\x18\t \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\n" +
	" \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\v \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\f \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\r \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vkernel_arch\x18\x0e \x01(\tR\n" +
	"kernelArch\x12\x17\n" +
	"\ahost_id\x18\x0f \x01(\tR\x06hostId\x12\x17\n" +
	"\acpu_num\x18\x10 \x01(\x05R\x06cpuNum\x12\x19\n" +
	"\bcpu_info\x18\x11 \x01(\tR\acpuInfo\x12\x1b\n" +
	"\tmem_total\x18\x12 \x01(\x04R\bmemTotal\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x13 \x01(\x04R\tdiskTotal\"/\n" +
	"\aAuthAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xc8\x02\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bmem_free\x18\x02 \x01(\x04R\amemFree\x12\x19\n" +
	"\bmem_used\x18\x03 \x01(\x04R\amemUsed\x12(\n" +
	"\x10mem_used_percent\x18\x04 \x01(\x01R\x0ememUsedPercent\x12#\n" +
	"\rmem_available\x18\x05 \x01(\x04R\fmemAvailable\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x120\n" +
	"\n" +
	"disk_usage\x18\a \x03(\v2\x11.packet.DiskUsageR\tdiskUsage\x12$\n" +
	"\x0enet_bytes_sent\x18\b \x01(\x01R\fnetBytesSent\x12$\n" +
	"\x0enet_bytes_recv\x18\t \x01(\x01R\fnetBytesRecv\"\xad\x02\n" +
	"\tDiskUsage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06fstype\x18\x02 \x01(\tR\x06fstype\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x12\n" +
	"\x04free\x18\x04 \x01(\x04R\x04free\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x04R\x04used\x12!\n" +
	"\fused_percent\x18\x06 \x01(\x01R\vusedPercent\x12!\n" +
	"\finodes_total\x18\a \x01(\x04R\vinodesTotal\x12\x1f\n" +
	"\vinodes_free\x18\b \x01(\x04R\n" +
	"inodesFree\x12\x1f\n" +
	"\vinodes_used\x18\t \x01(\x04R\n" +
	"inodesUsed\x12.\n" +
	"\x13inodes_used_percent\x18\n" +
	" \x01(\x01R\x11inodesUsedPercent\"\x98\x01\n" +
	"\n" +
	"OpenTunnel\x12?\n" +
	"\vtunnel_type\x18\x01 \x01(\x0e2\x1e.packet.OpenTunnel.TuunnelTypeR\n" +
	"tunnelType\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"5\n" +
	"\vTuunnelType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03PTY\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02\x12\a\n" +
	"\x03UDP\x10\x03\"5\n" +
	"\rOpenTunnelAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"N\n" +
	"\aCommand\x12%\n" +
	"\x03cmd\x18\x01 \x01(\x0e2\x13.packet.Command.CmdR\x03cmd\"\x1c\n" +
	"\x03Cmd\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04EXIT\x10\x01B\x11Z\x0fnoah/pkg/packetb\x06proto3"

var (
	file_pkg_packet_message_proto_rawDescOnce sync.Once
	file_pkg_packet_message_proto_rawDescData []byte
)

func file_pkg_packet_message_proto_rawDescGZIP() []byte {
	file_pkg_packet_message_proto_rawDescOnce.Do(func() {
		file_pkg_packet_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_packet_message_proto_rawDesc), len(file_pkg_packet_message_proto_rawDesc)))
	})
	return file_pkg_packet_message_proto_rawDescData
}

var file_pkg_packet_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_packet_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_packet_message_proto_goTypes = []any{
	(OpenTunnel_TuunnelType)(0), // 0: packet.OpenTunnel.TuunnelType
	(Command_Cmd)(0),            // 1: packet.Command.Cmd
	(*Message)(nil),             // 2: packet.Message
	(*Auth)(nil),                // 3: packet.Auth
	(*AgentInfo)(nil),           // 4: packet.AgentInfo
	(*AuthAck)(nil),             // 5: packet.AuthAck
	(*Ping)(nil),                // 6: packet.Ping
	(*DiskUsage)(nil),           // 7: packet.DiskUsage
	(*OpenTunnel)(nil),          // 8: packet.OpenTunnel
	(*OpenTunnelAck)(nil),       // 9: packet.OpenTunnelAck
	(*Command)(nil),             // 10: packet.Command
	(*anypb.Any)(nil),           // 11: google.protobuf.Any
}
var file_pkg_packet_message_proto_depIdxs = []int32{
	11, // 0: packet.Message.body:type_name -> google.protobuf.Any
	4,  // 1: packet.Auth.agent_info:type_name -> packet.AgentInfo
	7,  // 2: packet.Ping.disk_usage:type_name -> packet.DiskUsage
	0,  // 3: packet.OpenTunnel.tunnel_type:type_name -> packet.OpenTunnel.TuunnelType
	1,  // 4: packet.Command.cmd:type_name -> packet.Command.Cmd
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_packet_message_proto_init() }
func file_pkg_packet_message_proto_init() {
	if File_pkg_packet_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_packet_message_proto_rawDesc), len(file_pkg_packet_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_packet_message_proto_goTypes,
		DependencyIndexes: file_pkg_packet_message_proto_depIdxs,
		EnumInfos:         file_pkg_packet_message_proto_enumTypes,
		MessageInfos:      file_pkg_packet_message_proto_msgTypes,
	}.Build()
	File_pkg_packet_message_proto = out.File
	file_pkg_packet_message_proto_goTypes = nil
	file_pkg_packet_message_proto_depIdxs = nil
}
