#!/bin/bash

# 检查是否传入 host 和 token 参数
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  echo "Usage: $0 <host> <port> <token>"
  exit 1
fi

HOST=$1
PORT=$2
TOKEN=$3

# 获取系统信息
OS_NAME=$(uname -s | tr '[:upper:]' '[:lower:]')  # 转换为小写
CPU_ARCH=$(uname -m)

# 映射 CPU 架构
case $CPU_ARCH in
  x86_64)
    GOARCH=amd64
    ;;
  i386)
    GOARCH=386
    ;;
  armv6l)
    GOARCH=arm
    ;;
  armv7l)
    GOARCH=arm
    ;;
  aarch64)
    GOARCH=arm64
    ;;
  *)
    echo "Unsupported CPU architecture: $CPU_ARCH"
    exit 1
    ;;
esac

# 设置 GOOS
GOOS=$OS_NAME

# 构建 API URL
API_URL="http://${HOST}:${PORT}/api/client/build?token=${TOKEN}&goos=${GOOS}&goarch=${GOARCH}"

# 检查是否有 curl 命令
if command -v curl >/dev/null 2>&1; then
  # 使用 curl 下载文件
  curl -kfsSL $API_URL -o noah-cli
else
  # 使用 wget 下载文件
  if command -v wget >/dev/null 2>&1; then
    wget -qO- $API_URL -O noah-cli
  else
    echo "Neither curl nor wget is installed. Please install one of them."
    exit 1
  fi
fi

# 赋予执行权限
chmod +x noah-cli

# 执行文件
./noah-cli run -d --host $HOST --port $PORT