/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonTable: typeof import('./components/common/Table.vue')['default']
    Locales: typeof import('./components/locales/index.vue')['default']
    Logo: typeof import('./components/logo/index.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    Preview: typeof import('./components/theme/preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/common/Search.vue')['default']
    Table: typeof import('./components/common/Table.vue')['default']
    TableContent: typeof import('./components/common/TableContent.vue')['default']
    Theme: typeof import('./components/theme/index.vue')['default']
    UserInfo: typeof import('./components/user/user-info.vue')['default']
  }
}
