// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "支持手机验证码、密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/response.LoginResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/response.UserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "loginType",
                "username"
            ],
            "properties": {
                "code": {
                    "description": "验证码登录时必填",
                    "type": "string"
                },
                "loginType": {
                    "description": "1:验证码登录 2:密码登录",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "password": {
                    "description": "密码登录时必填",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "username": {
                    "description": "用户名或者手机号",
                    "type": "string"
                }
            }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "response.UserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "work_space_list": {
                    "description": "工作空间列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.WorkSpaceResponse"
                    }
                }
            }
        },
        "response.WorkSpaceAppResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "应用描述",
                    "type": "string"
                },
                "id": {
                    "description": "应用ID",
                    "type": "integer"
                },
                "name": {
                    "description": "应用名称",
                    "type": "string"
                },
                "status": {
                    "description": "应用状态",
                    "type": "integer"
                }
            }
        },
        "response.WorkSpaceResponse": {
            "type": "object",
            "properties": {
                "app_list": {
                    "description": "应用列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.WorkSpaceAppResponse"
                    }
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "工作空间描述",
                    "type": "string"
                },
                "id": {
                    "description": "工作空间ID",
                    "type": "integer"
                },
                "name": {
                    "description": "工作空间名称",
                    "type": "string"
                },
                "status": {
                    "description": "工作空间状态",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Noah API",
	Description:      "This is a sample server for Noah API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
